In [1]:
# This is going to be project achievement 6 so this is 6.1

CareerFoundryTask 6.1 

0.1 This is Importing Libraries
0.2 This is Importing Data
0.3 This is Data Wrangling/Cleaning
0.4 This is Exploring stats
    This is  0.4A Is there a relationship between 'Cocoa Percent' and 
         'Number_of_Ingredients for each country
0.5 This is Exporting data

0.1 IMPORTING THE LIBRARIES

In [2]:
# Importing the  libraries
import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt
import seaborn as sns
import scipy

0.2.  IMPORTING THE DATA

In [3]:
# In simpler terms, this code represents the location of a file named on this computer
r"C:\Users\rdpor\anaconda3\Scripts\CAREER FOUNDRY ACHIEVMENT 6\Original Data\chocolate_bar_ratings.csv"

'C:\\Users\\rdpor\\anaconda3\\Scripts\\CAREER FOUNDRY ACHIEVMENT 6\\Original Data\\chocolate_bar_ratings.csv'

In [4]:

path = r'C:\Users\rdpor\anaconda3\Scripts\CAREER FOUNDRY ACHIEVMENT 6\Original Data\chocolate_bar_ratings.csv'

In [5]:
# This code is checking the path
path

'C:\\Users\\rdpor\\anaconda3\\Scripts\\CAREER FOUNDRY ACHIEVMENT 6\\Original Data\\chocolate_bar_ratings.csv'

In [6]:
# importing the chocolate bar ratings data frame
choc_bar_ratings_df = pd.read_csv(r'C:\Users\rdpor\anaconda3\Scripts\CAREER FOUNDRY ACHIEVMENT 6\Original Data\chocolate_bar_ratings.csv', index_col = False)

In [7]:
# Double checking the import to make sure we are good
choc_bar_ratings_df.head()

,REF,Company (Manufacturer),Company Location,Review Date,Country of Bean Origin,Specific Bean Origin or Bar Name,Cocoa Percent,Ingredients,Most Memorable Characteristics,Rating
0,1003,Manoa,U.S.A.,2012.0,Liberia,"Liberia, batch 174",0.76,"3- B,S,C","molassses, intense, off, herb",3.25
1,1007,Manoa,U.S.A.,2012.0,U.S.A.,"Hawai'i Island, Hamakua, Hawaiian Crown, b. 176",0.76,"3- B,S,C","oily, tangy, fruit, earthy",2.75
2,1007,Manoa,U.S.A.,2012.0,Peru,"Piura, batch 173",0.76,"3- B,S,C","banana, menthol, medicinal",3.00
3,1007,Manoa,U.S.A.,2012.0,U.S.A.,"O'ahu Island, Winward,Maunawili district, b. 151",0.68,"3- B,S,C","molasses, sweet, cocoa",3.25
4,1007,Nanea,U.S.A.,2013.0,U.S.A.,Criollo Blend,0.72,,"sandy, spicy, earthy",3.50

In [8]:
# # ***Note: this is from  the flavors of cacao website https://flavorsofcacao.com/flavor.html
# New! Ingredients column ("#" = represents the number of ingredients in the chocolate; 
#  B = Beans, S = Sugar, S* = Sweetener other than white cane or beet sugar,
# C = Cocoa Butter, V = Vanilla, L = Lecithin, Sa = Salt)
# In other words the actual number in the column is the quantity of ingredients
# and the letters that follow are the specific type of ingredients
# I.E. C = Cocoa Butter

In [9]:
# Assessing the # of rows and columns in the chocolate bar data frame
choc_bar_ratings_df.shape

(2657, 10)

In [10]:
choc_bar_ratings_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2657 entries, 0 to 2656
Data columns (total 10 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   REF                               2657 non-null   int64
 1   Company (Manufacturer)            2656 non-null   object
 2   Company Location                  2656 non-null   object
 3   Review Date                       2656 non-null   float64
 4   Country of Bean Origin            2656 non-null   object
 5   Specific Bean Origin or Bar Name  2656 non-null   object
 6   Cocoa Percent                     2657 non-null   float64
 7   Ingredients                       2656 non-null   object
 8   Most Memorable Characteristics    2656 non-null   object
 9   Rating                            2656 non-null   float64
dtypes: float64(3), int64(1), object(6)
memory usage: 207.7+ KB

3. wrangling and cleaning

In [11]:
# dropping the unnecessary column named  "REF"
choc_bar_ratings_df = choc_bar_ratings_df.drop(columns = ['REF'])

In [12]:
#double checking to make sure the 'REF' column dropped
choc_bar_ratings_df

,Company (Manufacturer),Company Location,Review Date,Country of Bean Origin,Specific Bean Origin or Bar Name,Cocoa Percent,Ingredients,Most Memorable Characteristics,Rating
0,Manoa,U.S.A.,2012.0,Liberia,"Liberia, batch 174",0.76,"3- B,S,C","molassses, intense, off, herb",3.25
1,Manoa,U.S.A.,2012.0,U.S.A.,"Hawai'i Island, Hamakua, Hawaiian Crown, b. 176",0.76,"3- B,S,C","oily, tangy, fruit, earthy",2.75
2,Manoa,U.S.A.,2012.0,Peru,"Piura, batch 173",0.76,"3- B,S,C","banana, menthol, medicinal",3.00
3,Manoa,U.S.A.,2012.0,U.S.A.,"O'ahu Island, Winward,Maunawili district, b. 151",0.68,"3- B,S,C","molasses, sweet, cocoa",3.25
4,Nanea,U.S.A.,2013.0,U.S.A.,Criollo Blend,0.72,,"sandy, spicy, earthy",3.50
...,...,...,...,...,...,...,...,...,...
2652,Bahen & Co.,Australia,2012.0,Madagascar,Sambirano,0.80,"2- B,S","unrefined, flat, grassy",3.00
2653,Mast Brothers,U.S.A.,2012.0,Blend,Madagascar,0.75,"2- B,S","gritty, overly tart, sour",2.50
2654,Mast Brothers,U.S.A.,2012.0,Venezuela,Chuao,0.75,"2- B,S","gritty, sour, sweet",2.75
2655,Bahen & Co.,Australia,2012.0,Brazil,Bahia,0.70,"2- B,S","chalky, intense, chemical",2.50
2656,NaN,NaN,NaN,NaN,NaN,0.72,NaN,NaN,NaN

In [13]:
# double checking the shape 
choc_bar_ratings_df.shape

(2657, 9)

In [14]:
# assessing the overall head and shape of the data frame
choc_bar_ratings_df.head()

,Company (Manufacturer),Company Location,Review Date,Country of Bean Origin,Specific Bean Origin or Bar Name,Cocoa Percent,Ingredients,Most Memorable Characteristics,Rating
0,Manoa,U.S.A.,2012.0,Liberia,"Liberia, batch 174",0.76,"3- B,S,C","molassses, intense, off, herb",3.25
1,Manoa,U.S.A.,2012.0,U.S.A.,"Hawai'i Island, Hamakua, Hawaiian Crown, b. 176",0.76,"3- B,S,C","oily, tangy, fruit, earthy",2.75
2,Manoa,U.S.A.,2012.0,Peru,"Piura, batch 173",0.76,"3- B,S,C","banana, menthol, medicinal",3.00
3,Manoa,U.S.A.,2012.0,U.S.A.,"O'ahu Island, Winward,Maunawili district, b. 151",0.68,"3- B,S,C","molasses, sweet, cocoa",3.25
4,Nanea,U.S.A.,2013.0,U.S.A.,Criollo Blend,0.72,,"sandy, spicy, earthy",3.50

In [15]:
#double checking the info
choc_bar_ratings_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2657 entries, 0 to 2656
Data columns (total 9 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Company (Manufacturer)            2656 non-null   object
 1   Company Location                  2656 non-null   object
 2   Review Date                       2656 non-null   float64
 3   Country of Bean Origin            2656 non-null   object
 4   Specific Bean Origin or Bar Name  2656 non-null   object
 5   Cocoa Percent                     2657 non-null   float64
 6   Ingredients                       2656 non-null   object
 7   Most Memorable Characteristics    2656 non-null   object
 8   Rating                            2656 non-null   float64
dtypes: float64(3), object(6)
memory usage: 186.9+ KB

In [16]:
# checking for any possible missing values
choc_bar_ratings_df.isnull().sum()

Company (Manufacturer)              1
Company Location                    1
Review Date                         1
Country of Bean Origin              1
Specific Bean Origin or Bar Name    1
Cocoa Percent                       0
Ingredients                         1
Most Memorable Characteristics      1
Rating                              1
dtype: int64

In [17]:

# New! Ingredients column ("#" = represents the number of ingredients in the chocolate; 
#  B = Beans, S = Sugar, S* = Sweetener other than white cane or beet sugar,
# C = Cocoa Butter, V = Vanilla, L = Lecithin, Sa = Salt)
# In other words the actual number in the column is the quantity of ingredients
# and the letters that follow are the specific type of ingredients
# I.E. C = Cocoa Butter

In [18]:
# now I am going to seperate the Ingredients column into two seperate columns 
# the reason behind this is because the Ingredients column has integers and strings 
# and I want more difintive clarity in my data set. So, the Ingredients column will 
# be split into a new "Num of Ingredients" column which is represented by an Integer/  #
# and another column that is "Specific Ingredients"

In [19]:
# Now I am going to be Sepperating the 'Ingredients' column into two separate columns'Num_of_Ingredients' and 'Specific Ingredients'
choc_bar_ratings_df[['Num_of_Ingredients', 'Specific Ingredients']] = choc_bar_ratings_df['Ingredients'].str.split('-', expand=True)

# Remove leading and trailing whitespace from both columns
choc_bar_ratings_df['Num_of_Ingredients'] = choc_bar_ratings_df['Num_of_Ingredients'].str.strip()
choc_bar_ratings_df['Specific Ingredients'] = choc_bar_ratings_df['Specific Ingredients'].str.strip()

In [20]:
# running the new data frame to assess the situation and see the new columns created
choc_bar_ratings_df.head()

,Company (Manufacturer),Company Location,Review Date,Country of Bean Origin,Specific Bean Origin or Bar Name,Cocoa Percent,Ingredients,Most Memorable Characteristics,Rating,Num_of_Ingredients,Specific Ingredients
0,Manoa,U.S.A.,2012.0,Liberia,"Liberia, batch 174",0.76,"3- B,S,C","molassses, intense, off, herb",3.25,3,"B,S,C"
1,Manoa,U.S.A.,2012.0,U.S.A.,"Hawai'i Island, Hamakua, Hawaiian Crown, b. 176",0.76,"3- B,S,C","oily, tangy, fruit, earthy",2.75,3,"B,S,C"
2,Manoa,U.S.A.,2012.0,Peru,"Piura, batch 173",0.76,"3- B,S,C","banana, menthol, medicinal",3.00,3,"B,S,C"
3,Manoa,U.S.A.,2012.0,U.S.A.,"O'ahu Island, Winward,Maunawili district, b. 151",0.68,"3- B,S,C","molasses, sweet, cocoa",3.25,3,"B,S,C"
4,Nanea,U.S.A.,2013.0,U.S.A.,Criollo Blend,0.72,,"sandy, spicy, earthy",3.50,,None

In [21]:
# what I'm doing here is dropping the 'Ingredients' column because I split it 
# into "Num of Ingredients" and "Specific Ingredients" columns

choc_bar_ratings_df=choc_bar_ratings_df.drop(columns = ['Ingredients'])

In [40]:
# converting to an integer and having missing value / null value with '0'
choc_bar_ratings_df['Num_of_Ingredients']=choc_bar_ratings_df['Num_of_Ingredients'].fillna(0).astype(int)

In [23]:
# checking new data set with the dropped "Ingredients column"
choc_bar_ratings_df.head()

,Company (Manufacturer),Company Location,Review Date,Country of Bean Origin,Specific Bean Origin or Bar Name,Cocoa Percent,Most Memorable Characteristics,Rating,Num_of_Ingredients,Specific Ingredients
0,Manoa,U.S.A.,2012.0,Liberia,"Liberia, batch 174",0.76,"molassses, intense, off, herb",3.25,3,"B,S,C"
1,Manoa,U.S.A.,2012.0,U.S.A.,"Hawai'i Island, Hamakua, Hawaiian Crown, b. 176",0.76,"oily, tangy, fruit, earthy",2.75,3,"B,S,C"
2,Manoa,U.S.A.,2012.0,Peru,"Piura, batch 173",0.76,"banana, menthol, medicinal",3.00,3,"B,S,C"
3,Manoa,U.S.A.,2012.0,U.S.A.,"O'ahu Island, Winward,Maunawili district, b. 151",0.68,"molasses, sweet, cocoa",3.25,3,"B,S,C"
4,Nanea,U.S.A.,2013.0,U.S.A.,Criollo Blend,0.72,"sandy, spicy, earthy",3.50,,None

In [24]:
choc_bar_ratings_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2657 entries, 0 to 2656
Data columns (total 10 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Company (Manufacturer)            2656 non-null   object
 1   Company Location                  2656 non-null   object
 2   Review Date                       2656 non-null   float64
 3   Country of Bean Origin            2656 non-null   object
 4   Specific Bean Origin or Bar Name  2656 non-null   object
 5   Cocoa Percent                     2657 non-null   float64
 6   Most Memorable Characteristics    2656 non-null   object
 7   Rating                            2656 non-null   float64
 8   Num_of_Ingredients                2656 non-null   object
 9   Specific Ingredients              2569 non-null   object
dtypes: float64(3), object(7)
memory usage: 207.7+ KB

In [25]:
# This is checking the data type of the "Num_of_Ingredients" column
choc_bar_ratings_df['Num_of_Ingredients'].dtype

dtype('O')

In [26]:
# addressing NaNs in 'Num_of_Ingredients'
# # ***Note: maybe delete this line of code as well. 
df_nan = choc_bar_ratings_df[choc_bar_ratings_df['Num_of_Ingredients'].isnull() == True]

In [27]:
# ***Note: maybe delete this line of code Ramón
df_nan

,Company (Manufacturer),Company Location,Review Date,Country of Bean Origin,Specific Bean Origin or Bar Name,Cocoa Percent,Most Memorable Characteristics,Rating,Num_of_Ingredients,Specific Ingredients
2656,NaN,NaN,NaN,NaN,NaN,0.72,NaN,NaN,NaN,NaN

In [28]:
# note: maybe fix this float stuf or maybe just delete it all in this cell 
# ***Note: might need to edit and fix this
# the whole point is to change the data type of number of ingredients in the chocolate column from object to numerical

In [29]:
choc_bar_ratings_df['Num_of_Ingredients'].replace('',0).value_counts()

3    1109
2     783
4     476
5     191
0      87
1       6
6       4
Name: Num_of_Ingredients, dtype: int64

In [30]:
# replacing a blank with a "0"
choc_bar_ratings_df['Num_of_Ingredients'].replace('',0,inplace= True)

In [31]:
choc_bar_ratings_df.dtypes

Company (Manufacturer)               object
Company Location                     object
Review Date                         float64
Country of Bean Origin               object
Specific Bean Origin or Bar Name     object
Cocoa Percent                       float64
Most Memorable Characteristics       object
Rating                              float64
Num_of_Ingredients                   object
Specific Ingredients                 object
dtype: object

In [32]:
# going to an integer na flin 
choc_bar_ratings_df['Num_of_Ingredients'].fillna(0).astype(int)

0       3
1       3
2       3
3       3
4       0
       ..
2652    2
2653    2
2654    2
2655    2
2656    0
Name: Num_of_Ingredients, Length: 2657, dtype: int32

In [33]:
# assessing the "num of ingredients"
# *** ***Question Note: you might have to go back and change the dtype so that it ends up being a Float 64 instead of an object
choc_bar_ratings_df['Num_of_Ingredients'].describe()

count     2656
unique       7
top          3
freq      1109
Name: Num_of_Ingredients, dtype: object

In [34]:
# Calculating some of the general statistics for 'Num_of_Ingredients'
choc_bar_ratings_df.groupby('Num_of_Ingredients').agg({'Cocoa Percent':['mean', 'min','max']})

                   Cocoa Percent
                            mean   min   max
Num_of_Ingredients
0                       0.712989  0.56  0.85
1                       0.703333  0.65  0.75
2                       0.714796  0.42  1.00
3                       0.716546  0.50  1.00
4                       0.719643  0.55  1.00
5                       0.712382  0.55  1.00
6                       0.710000  0.60  0.80

In [35]:
# ***Note: Flin 26 might need to go back and delete ? is this correct? 
# finding countries of 'Num_of_Ingredients' NaNs 
df_nan['Company Location'].unique()

array([nan], dtype=object)

In [36]:
# ***Note: FLin 27 might need to go back and delete ? is this correct? 
nan_countries = choc_bar_ratings_df.loc[choc_bar_ratings_df['Company Location'].isin (['U.S.A.', 'U.K.', 'Italy', 'Canada', 'Australia', 'Belgium',
       'Japan', 'Ecuador', 'Russia', 'South Korea', 'Sao Tome & Principe',
       'Argentina', 'Germany', 'France', 'Madagascar', 'Peru', 'Spain',
       'New Zealand', 'Poland', 'Brazil','Colombia'])]

In [37]:
# ***Note:  Flin 26 might need to go back and delete?
nan_countries

,Company (Manufacturer),Company Location,Review Date,Country of Bean Origin,Specific Bean Origin or Bar Name,Cocoa Percent,Most Memorable Characteristics,Rating,Num_of_Ingredients,Specific Ingredients
0,Manoa,U.S.A.,2012.0,Liberia,"Liberia, batch 174",0.76,"molassses, intense, off, herb",3.25,3,"B,S,C"
1,Manoa,U.S.A.,2012.0,U.S.A.,"Hawai'i Island, Hamakua, Hawaiian Crown, b. 176",0.76,"oily, tangy, fruit, earthy",2.75,3,"B,S,C"
2,Manoa,U.S.A.,2012.0,Peru,"Piura, batch 173",0.76,"banana, menthol, medicinal",3.00,3,"B,S,C"
3,Manoa,U.S.A.,2012.0,U.S.A.,"O'ahu Island, Winward,Maunawili district, b. 151",0.68,"molasses, sweet, cocoa",3.25,3,"B,S,C"
4,Nanea,U.S.A.,2013.0,U.S.A.,Criollo Blend,0.72,"sandy, spicy, earthy",3.50,0,None
...,...,...,...,...,...,...,...,...,...,...
2651,Madre,U.S.A.,2012.0,U.S.A.,Kaua'i Island,0.70,"vanilla, brownie, peanut",3.50,4,"B,S,C,V"
2652,Bahen & Co.,Australia,2012.0,Madagascar,Sambirano,0.80,"unrefined, flat, grassy",3.00,2,"B,S"
2653,Mast Brothers,U.S.A.,2012.0,Blend,Madagascar,0.75,"gritty, overly tart, sour",2.50,2,"B,S"
2654,Mast Brothers,U.S.A.,2012.0,Venezuela,Chuao,0.75,"gritty, sour, sweet",2.75,2,"B,S"
2655,Bahen & Co.,Australia,2012.0,Brazil,Bahia,0.70,"chalky, intense, chemical",2.50,2,"B,S"

In [41]:
# ***Note: Flin 29 might need to go back and delete ? is this correct? 
# ***Question T
# finding stats for countries of 'Number_of_Ingredients' NaNs
nan_countries.groupby('Company Location')['Num_of_Ingredients'].agg(['min', 'max', 'mean', 'median'])

TypeError: '<=' not supported between instances of 'str' and 'int'

In [42]:
# ***Note: Flin 30 might need to go back and delete ? is this correct? 
# creating dictionary and map to replace NaN specific to each country ('Compnay Location')
replacement_values = {
    'Argentina': 4,  # Replace NaN for Argentina with 4, etc.
    'Australia': 3,  
    'Belgium': 4,
    'Brazil': 3,  
    'Canada': 3,
    'Colombia': 4,
    'Ecuador': 4,
    'France': 4,
    'Germany': 3,
    'Italy': 3,
    'Japan': 3,
    'Madagascar': 4,
    'New Zealand': 2,
    'Peru': 3,
    'Poland': 2,
    'Russia': 2,
    'Sao Tome & Principe': 3,
    'South Korea': 2,
    'Spain': 3,
    'U.K.': 3,
    'U.S.A.': 3
}

In [44]:
# ***Note: Flin 31 might need to go back and delete ? is this correct? 
# Define a custom function to replace NaN values
def replace_nan(row):
    location = row['Company Location']
    replacement = replacement_values.get(location)
    if pd.isna(row['Num_of_Ingredients']):
        return replacement
    else:
        return row['Num_of_Ingredients']

# Apply the custom function to replace NaN values in 'Num_of_Ingredients'
choc_bar_ratings_df['Num_of_Ingredients'] = choc_bar_ratings_df.apply(replace_nan, axis=1)

***Note: from line 31 might need to go back and delete ? is this correct?
 
The nan values in the "Num_of_Ingredients" for every company location in "choc_bar_ratings_df" were replaced with more 
specific values.

In [45]:
# ***Note: Flin 32 might need to go back and delete  

# This is checking choc_bar_ratings_df for NaNs again
choc_bar_ratings_df.isnull().sum()

Company (Manufacturer)               1
Company Location                     1
Review Date                          1
Country of Bean Origin               1
Specific Bean Origin or Bar Name     1
Cocoa Percent                        0
Most Memorable Characteristics       1
Rating                               1
Num_of_Ingredients                   0
Specific Ingredients                88
dtype: int64

In [46]:
# ***Note: Flin 33 might need to go back and delete 
choc_bar_ratings_df['Num_of_Ingredients'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 2657 entries, 0 to 2656
Series name: Num_of_Ingredients
Non-Null Count  Dtype
--------------  -----
2657 non-null   int64
dtypes: int64(1)
memory usage: 20.9 KB

In [47]:
# 
choc_bar_ratings_df

,Company (Manufacturer),Company Location,Review Date,Country of Bean Origin,Specific Bean Origin or Bar Name,Cocoa Percent,Most Memorable Characteristics,Rating,Num_of_Ingredients,Specific Ingredients
0,Manoa,U.S.A.,2012.0,Liberia,"Liberia, batch 174",0.76,"molassses, intense, off, herb",3.25,3,"B,S,C"
1,Manoa,U.S.A.,2012.0,U.S.A.,"Hawai'i Island, Hamakua, Hawaiian Crown, b. 176",0.76,"oily, tangy, fruit, earthy",2.75,3,"B,S,C"
2,Manoa,U.S.A.,2012.0,Peru,"Piura, batch 173",0.76,"banana, menthol, medicinal",3.00,3,"B,S,C"
3,Manoa,U.S.A.,2012.0,U.S.A.,"O'ahu Island, Winward,Maunawili district, b. 151",0.68,"molasses, sweet, cocoa",3.25,3,"B,S,C"
4,Nanea,U.S.A.,2013.0,U.S.A.,Criollo Blend,0.72,"sandy, spicy, earthy",3.50,0,None
...,...,...,...,...,...,...,...,...,...,...
2652,Bahen & Co.,Australia,2012.0,Madagascar,Sambirano,0.80,"unrefined, flat, grassy",3.00,2,"B,S"
2653,Mast Brothers,U.S.A.,2012.0,Blend,Madagascar,0.75,"gritty, overly tart, sour",2.50,2,"B,S"
2654,Mast Brothers,U.S.A.,2012.0,Venezuela,Chuao,0.75,"gritty, sour, sweet",2.75,2,"B,S"
2655,Bahen & Co.,Australia,2012.0,Brazil,Bahia,0.70,"chalky, intense, chemical",2.50,2,"B,S"
2656,NaN,NaN,NaN,NaN,NaN,0.72,NaN,NaN,0,NaN

In [48]:
# ***Note: Flin 34 might need to go back and delete
# double checking the choc_bar_ratings_df again
#***question: why am I not seeing all 75 rows?
choc_bar_ratings_df.head(75)

,Company (Manufacturer),Company Location,Review Date,Country of Bean Origin,Specific Bean Origin or Bar Name,Cocoa Percent,Most Memorable Characteristics,Rating,Num_of_Ingredients,Specific Ingredients
0,Manoa,U.S.A.,2012.0,Liberia,"Liberia, batch 174",0.76,"molassses, intense, off, herb",3.25,3,"B,S,C"
1,Manoa,U.S.A.,2012.0,U.S.A.,"Hawai'i Island, Hamakua, Hawaiian Crown, b. 176",0.76,"oily, tangy, fruit, earthy",2.75,3,"B,S,C"
2,Manoa,U.S.A.,2012.0,Peru,"Piura, batch 173",0.76,"banana, menthol, medicinal",3.00,3,"B,S,C"
3,Manoa,U.S.A.,2012.0,U.S.A.,"O'ahu Island, Winward,Maunawili district, b. 151",0.68,"molasses, sweet, cocoa",3.25,3,"B,S,C"
4,Nanea,U.S.A.,2013.0,U.S.A.,Criollo Blend,0.72,"sandy, spicy, earthy",3.50,0,None
...,...,...,...,...,...,...,...,...,...,...
70,Millcreek Cacao Roasters,U.S.A.,2013.0,Ecuador,Ecuador,0.60,"unrefined, burnt nuts, vanilla",2.50,4,"B,S,C,V"
71,Soma,Canada,2013.0,Peru,"Apurimac, El Quinacho Co-op",0.60,"creamy, medicinal, mild fruit",2.75,3,"B,S,C"
72,Soma,Canada,2013.0,Trinidad,Sangre Grande P.,0.60,"creamy, brownie mix, roasty",3.75,3,"B,S,C"
73,Soma,Canada,2013.0,Blend,Chef's Blend,0.60,"grassy, dairy, mild fatty",3.25,3,"B,S,C"
74,Soma,Canada,2013.0,Venezuela,Patanemo,0.60,"nutty, chocolate ice cream",3.75,3,"B,S,C"

In [49]:
# this is checking to see if there are any duplicates or not
# ***Note: Flin 35 might need to go back and delete  


choc_bar_ratings_df.describe()

       Review Date  Cocoa Percent       Rating  Num_of_Ingredients
count  2656.000000    2657.000000  2656.000000         2657.000000
mean   2014.750753       0.716131     3.198795            2.928867
std       4.220790       0.055345     0.441614            1.037975
min    2006.000000       0.420000     1.000000            0.000000
25%    2012.000000       0.700000     3.000000            2.000000
50%    2015.000000       0.700000     3.250000            3.000000
75%    2018.000000       0.740000     3.500000            4.000000
max    2023.000000       1.000000     4.000000            6.000000

In [50]:
# ***Note: Flin 36 might need to go back and delete
duplicates_df = choc_bar_ratings_df[choc_bar_ratings_df.duplicated()]

In [51]:
# looking for duplicates.
duplicates_df

Empty DataFrame
Columns: [Company (Manufacturer), Company Location, Review Date, Country of Bean Origin, Specific Bean Origin or Bar Name, Cocoa Percent, Most Memorable Characteristics, Rating, Num_of_Ingredients, Specific Ingredients]
Index: []

We can see that there's no duplicates

0.4 Exploring Stats


The list of NaN countries is not the most full and complete countires listed in 'Company Location'

In [52]:
# # ***Note: Flin 38 might need to go back and delete 
# what this is doing is finding all the countires listed in 'Company Location' from df_flavors
choc_bar_ratings_df['Company Location'].unique()

array(['U.S.A.', 'France', 'Canada', 'U.K.', 'Denmark', 'Lithuania',
       'Spain', 'Puerto Rico', 'Costa Rica', 'Switzerland', 'Brazil',
       'Dominican Republic', 'Madagascar', 'Italy', 'Belgium',
       'Philippines', 'Scotland', 'Peru', 'St. Lucia', 'Vietnam',
       'Martinique', 'Ireland', 'Germany', 'Australia', 'Hungary',
       'Austria', 'Guatemala', 'Finland', 'Iceland', 'Poland',
       'New Zealand', 'Sweden', 'Ecuador', 'South Africa', 'Colombia',
       'Honduras', 'Venezuela', 'Japan', 'Israel', 'Netherlands',
       'Czech Republic', 'Chile', 'Russia', 'South Korea', 'Portugal',
       'Singapore', 'India', 'Mexico', 'Suriname', 'U.A.E.',
       'Sao Tome & Principe', 'Nicaragua', 'Taiwan', 'Norway', 'Thailand',
       'St.Vincent-Grenadines', 'Malaysia', 'El Salvador', 'Grenada',
       'Vanuatu', 'Bolivia', 'France (Reunion)', 'Argentina', 'Ghana',
       'Fiji', 'Wales', nan], dtype=object)

In [53]:
# # ***Note: Flin 39 might need to go back and delete 
# finding the number of countires listed in 'Company Location' from df_flavors
choc_bar_ratings_df['Company Location'].nunique()

66

What My question now is: Is there a direct correlation between 
"Num_of_Ingredients" and "Cocoa Percent" partaining to every country.

In [54]:
# ***Question:  is anything wrong here?  ***Question: 
# line 40

# Is there a direct correlation between 
# "Num_of_Ingredients" and "Cocoa Percent" partaining to every country.
choc_bar_ratings_df.groupby('Company Location')[['Cocoa Percent','Num_of_Ingredients']].agg(['min', 'max', 'mean', 'median'])

                 Cocoa Percent                        Num_of_Ingredients      \
                           min   max      mean median                min max
Company Location
Argentina                 0.70  0.75  0.744444  0.750                  0   4
Australia                 0.65  0.80  0.714615  0.700                  0   5
Austria                   0.60  0.90  0.726000  0.700                  2   4
Belgium                   0.55  0.85  0.712917  0.700                  0   5
Bolivia                   0.73  0.80  0.765000  0.765                  4   4
...                        ...   ...       ...    ...                ...  ..
U.S.A.                    0.42  1.00  0.715356  0.700                  0   5
Vanuatu                   0.62  0.75  0.692500  0.700                  2   2
Venezuela                 0.60  0.90  0.700323  0.700                  2   5
Vietnam                   0.64  0.90  0.712778  0.700                  2   5
Wales                     0.70  0.70  0.700000  0.700                  4   4


                      mean median
Company Location
Argentina         1.777778    0.0
Australia         2.980769    3.0
Austria           3.533333    4.0
Belgium           3.652778    3.5
Bolivia           4.000000    4.0
...                    ...    ...
U.S.A.            2.784590    3.0
Vanuatu           2.000000    2.0
Venezuela         3.193548    3.0
Vietnam           2.944444    3.0
Wales             4.000000    4.0

[66 rows x 8 columns]

In [55]:
# looking into each 'Num_of_ingredients' cocoa percent values
# see line 43

choc_bar_ratings_df.groupby('Num_of_Ingredients')['Cocoa Percent'].unique()

Num_of_Ingredients
0    [0.72, 0.63, 0.7, 0.75, 0.85, 0.71, 0.65, 0.68...
1                        [0.7, 0.68, 0.74, 0.75, 0.65]
2    [0.7, 0.63, 0.66, 0.72, 0.75, 0.8, 0.83, 0.73,...
3    [0.76, 0.68, 0.7, 0.74, 0.88, 0.72, 0.75, 0.6,...
4    [0.8, 0.68, 0.78, 0.7, 0.63, 0.6, 0.75, 0.85, ...
5    [0.8, 0.7, 0.55, 0.75, 0.65, 0.6, 0.73, 0.72, ...
6                                     [0.8, 0.72, 0.6]
Name: Cocoa Percent, dtype: object

In [56]:
# see line 43
#
# what this is doing is looking into each country's 'Cocoa Percent'
choc_bar_ratings_df.groupby('Company Location')['Cocoa Percent'].unique()

Company Location
Argentina                                          [0.75, 0.7]
Australia    [0.72, 0.7, 0.75, 0.78, 0.74, 0.68, 0.65, 0.69...
Austria      [0.82, 0.6, 0.7, 0.79, 0.78, 0.8, 0.68, 0.66, ...
Belgium      [0.7, 0.73, 0.6, 0.68, 0.77, 0.71, 0.8, 0.75, ...
Bolivia                                            [0.8, 0.73]
                                   ...
U.S.A.       [0.76, 0.68, 0.72, 0.7, 0.63, 0.74, 0.55, 0.6,...
Vanuatu                                      [0.7, 0.75, 0.62]
Venezuela    [0.7, 0.6, 0.75, 0.72, 0.66, 0.65, 0.61, 0.67,...
Vietnam              [0.7, 0.72, 0.725, 0.75, 0.64, 0.66, 0.9]
Wales                                                    [0.7]
Name: Cocoa Percent, Length: 66, dtype: object

In [57]:
# what this is doing is looking into a specific country for examples
#  what this is doing is looking into the United States info as it has a wide variety of stats
USA = choc_bar_ratings_df[choc_bar_ratings_df['Company Location'] == 'USA']

In [58]:
# Flin 44 
USA

Empty DataFrame
Columns: [Company (Manufacturer), Company Location, Review Date, Country of Bean Origin, Specific Bean Origin or Bar Name, Cocoa Percent, Most Memorable Characteristics, Rating, Num_of_Ingredients, Specific Ingredients]
Index: []

In [59]:
# Flin 45 what this is doing is going into some more details and specifics on the  data, there's not much here obviously
USA.groupby('Num_of_Ingredients')['Cocoa Percent'].unique()

Series([], Name: Cocoa Percent, dtype: float64)

In [60]:
# from Flin 45 
# what this is doing is looking into a specific country for examples
#  what this is doing is looking into Australia info as it contains a much  larger variety of stats
Australia = choc_bar_ratings_df[choc_bar_ratings_df['Company Location'] == 'Australia']

In [61]:
Australia

,Company (Manufacturer),Company Location,Review Date,Country of Bean Origin,Specific Bean Origin or Bar Name,Cocoa Percent,Most Memorable Characteristics,Rating,Num_of_Ingredients,Specific Ingredients
179,Matale,Australia,2013.0,Vanuatu,"Malekula P., 2013",0.72,"sticky, butterscotch, nutty",3.50,3,"B,S,C"
180,Matale,Australia,2013.0,Madagascar,"Somia, 2013",0.72,"sticky, red fruit",4.00,3,"B,S,C"
181,Matale,Australia,2013.0,Papua New Guinea,"Kulili P., 2013",0.72,"creamy, grassy, smoke, nut",4.00,3,"B,S,C"
183,Matale,Australia,2013.0,Blend,"PNG, Vanuatu, Mad; 2013 h.",0.72,"nutty, fruity, spicy",3.75,3,"B,S,C"
238,Bright,Australia,2014.0,Madagascar,Somia Plantation,0.70,"sweet, mild molasses, bland",3.00,3,"B,S,C"
239,Bright,Australia,2014.0,Dominican Republic,Marabel Farms,0.70,"spicy, black pepper, banana",3.50,3,"B,S,C"
240,Bright,Australia,2014.0,Ecuador,"Camino Verde, Balao, Guayas",0.75,"floral, banana",3.50,3,"B,S,C"
242,Bright,Australia,2014.0,Trinidad,Gran Couva,0.78,"fatty, sweet, metallic",2.75,3,"B,S,C"
289,Cravve,Australia,2014.0,Papua New Guinea,"New Ireland, batch 1702",0.70,"true to sugar, molasses",2.50,3,"B,S,C"
350,Cravve,Australia,2014.0,Vanuatu,"Vanuatu, batch 2410",0.70,banana nut,2.75,3,"B,S,C"
407,Monsieur Truffe,Australia,2014.0,Papua New Guinea,Papaua New Guinea,0.75,"smoke, ham, sour milk",3.25,0,None
455,Spencer,Australia,2014.0,Vanuatu,Malekula Island,0.75,"bready, sour milk, fatty",2.75,3,"B,S,C"
522,Bahen & Co.,Australia,2015.0,Blend,Houseblend,0.72,"coarse, smokey, metallic",3.25,2,"B,S"
523,Bahen & Co.,Australia,2015.0,Papua New Guinea,Papua New Guinea,0.74,"smoke, ham, papaya",3.50,2,"B,S"
679,"Smooth Chocolator, The",Australia,2015.0,Madagascar,Akesson's Estate,0.70,"few grits, sweet, orange",3.25,3,"B,S,C"
684,"Smooth Chocolator, The",Australia,2015.0,Madagascar,Akesson's Estate,0.70,"few grits, bold, dark berry",3.50,3,"B,S,C"
685,"Smooth Chocolator, The",Australia,2015.0,Tanzania,Kokoa Kamili,0.70,"bold cherry, rich cooa",3.75,3,"B,S,C"
686,"Smooth Chocolator, The",Australia,2015.0,Trinidad,San Juan Estate,0.70,"cigar, tobacco, grass, spice",3.75,3,"B,S,C"
687,"Smooth Chocolator, The",Australia,2015.0,Ecuador,Camino Verde,0.70,"creamy, pistachio, floral",4.00,3,"B,S,C"
689,"Smooth Chocolator, The",Australia,2015.0,Bolivia,Bolivia,0.68,"floral, intense, pungent",2.75,3,"B,S,C"
718,Daintree,Australia,2015.0,Australia,Goodman Estate,0.70,"sandy, candy like vanilla, off",2.75,3,"B,S,C"
727,"Smooth Chocolator, The",Australia,2015.0,Papua New Guinea,"Papua New Guinea, triple roast, batch 1",0.70,"smokey, tart, astringent",3.50,3,"B,S,C"
731,"Smooth Chocolator, The",Australia,2015.0,Peru,"Maranon, batch 2",0.72,"light brown, grits, floral",3.00,3,"B,S,C"
732,"Smooth Chocolator, The",Australia,2015.0,Venezuela,"Chuao, batch 3",0.70,mild cacao and fruit notes,3.75,3,"B,S,C"
785,Zokoko,Australia,2016.0,Solomon Islands,Guadalcanal,0.65,"smokey, dried fruit, balanced",3.75,4,"B,S,C,L"
807,"Smooth Chocolator, The",Australia,2016.0,Venezuela,"Guasare, La Sierra de Perija, batch gua001",0.70,"creamy, fruit, cocoa",3.75,3,"B,S,C"
808,"Smooth Chocolator, The",Australia,2016.0,Ecuador,"Porcelana, Sorotaima,Machiques,batch pcl001",0.70,"ligt color, creamy, peanut",4.00,3,"B,S,C"
828,"Smooth Chocolator, The",Australia,2016.0,Belize,"Maya Mtn, Moho R., Toledo D.",0.72,"apple, mild cherry",3.75,3,"B,S,C"
855,Zokoko,Australia,2016.0,Blend,Goddess Blend,0.70,"oily, sweet, choco, nutty",3.25,5,"B,S,C,V,L"
865,Spencer,Australia,2016.0,Dominican Republic,"Dominican Republic, lot D82R",0.70,"spicy, chocolatey",3.50,3,"B,S,C"
866,Spencer,Australia,2016.0,Ecuador,"Ecuador, lot E432314L",0.70,"floral, sandy",3.75,3,"B,S,C"
867,Spencer,Australia,2016.0,Madagascar,"Madagascar, lot M0403R",0.70,"powdery, cherry, astringent",3.75,3,"B,S,C"
943,"Smooth Chocolator, The",Australia,2016.0,Vietnam,Tien Giang,0.72,"creamy, molasses, off note",3.00,3,"B,S,C"
944,"Smooth Chocolator, The",Australia,2016.0,Australia,Australia,0.68,"delicate, smooth, dairy",3.75,3,"B,S,C"
990,"Smooth Chocolator, The",Australia,2016.0,Guatemala,"Chimelb, Lanquin, Alta Verapaz, b-GUA001",0.70,"gummy, fatty, earthy",3.25,3,"B,S,C"
1026,"Smooth Chocolator, The",Australia,2017.0,Dominican Republic,"Oko Caribe, DOR005",0.69,"cherry, rich choco",3.50,3,"B,S,C"
1038,"Smooth Chocolator, The",Australia,2017.0,Haiti,"Pisa, batch HA102",0.70,"complex, earthy, melon",3.50,3,"B,S,C"
1266,Metiisto,Australia,2018.0,Solomon Islands,"Patovaki, Paspaskato Is",0.70,"roasty/smokey, high acidity",3.25,3,"B,S,C"
1269,Metiisto,Australia,2018.0,Solomon Islands,Tenaru,0.80,"dried fruit, mild hammy",3.75,3,"B,S,C"
1560,Atypic,Australia,2019.0,Solomon Islands,Solomon Islands,0.70,"off aroma,vegetal,honey,sandy",3.00,4,"B,S,C,L"
2354,Zokoko,Australia,2011.0,Bolivia,Alto Beni,0.70,"oily, honey, light rum",3.50,4,"B,S,C,L"
2357,Haigh,Australia,2011.0,Blend,South America and Africa,0.72,"vanilla, chocolate milk",3.00,0,None
2359,Zokoko,Australia,2011.0,Papua New Guinea,Tokiala,0.77,"toffee, caramel, butterscotch",3.50,4,"B,S,C,L"
2360,Zokoko,Australia,2011.0,Bolivia,"Tranquilidad, Baures",0.80,intense prune and berry,3.75,4,"B,S,C,L"
2442,Daintree,Australia,2011.0,Australia,"Daintree Estates, N. Queensland",0.75,"vanilla, banana, citrus",3.25,5,"B,S,C,V,L"
2626,Cravve,Australia,2012.0,Tanzania,"Tanzania, batch a1",0.78,"spice, roasty, off fatty note",3.25,3,"B,S,C"
2627,Cravve,Australia,2012.0,Brazil,"Bahia, batch a1213",0.68,"sandy, sweet, smokey",3.25,3,"B,S,C"
2628,Cravve,Australia,2012.0,Fiji,"Namau Village, N. Taileva P., batch a2812",0.66,"acidic, sweet, cucumber",3.25,3,"B,S,C"
2629,Cravve,Australia,2012.0,Vanuatu,"Vanuatu, batch 2410",0.72,"sandy, sweet, spicy, roasty",3.25,3,"B,S,C"
2630,Cravve,Australia,2012.0,Papua New Guinea,"Djual Island, batch 1712",0.65,"sandy, sweet, nutty",3.50,3,"B,S,C"
2652,Bahen & Co.,Australia,2012.0,Madagascar,Sambirano,0.80,"unrefined, flat, grassy",3.00,2,"B,S"
2655,Bahen & Co.,Australia,2012.0,Brazil,Bahia,0.70,"chalky, intense, chemical",2.50,2,"B,S"

In [62]:
# flin 45 
# what this is doing is going into some more details and specifics on the Australia data
Australia.groupby('Num_of_Ingredients')['Cocoa Percent'].unique()

Num_of_Ingredients
0                                         [0.75, 0.72]
2                               [0.72, 0.74, 0.8, 0.7]
3    [0.72, 0.7, 0.75, 0.78, 0.68, 0.69, 0.8, 0.66,...
4                               [0.65, 0.7, 0.77, 0.8]
5                                          [0.7, 0.75]
Name: Cocoa Percent, dtype: object

In [63]:
choc_bar_ratings_df

,Company (Manufacturer),Company Location,Review Date,Country of Bean Origin,Specific Bean Origin or Bar Name,Cocoa Percent,Most Memorable Characteristics,Rating,Num_of_Ingredients,Specific Ingredients
0,Manoa,U.S.A.,2012.0,Liberia,"Liberia, batch 174",0.76,"molassses, intense, off, herb",3.25,3,"B,S,C"
1,Manoa,U.S.A.,2012.0,U.S.A.,"Hawai'i Island, Hamakua, Hawaiian Crown, b. 176",0.76,"oily, tangy, fruit, earthy",2.75,3,"B,S,C"
2,Manoa,U.S.A.,2012.0,Peru,"Piura, batch 173",0.76,"banana, menthol, medicinal",3.00,3,"B,S,C"
3,Manoa,U.S.A.,2012.0,U.S.A.,"O'ahu Island, Winward,Maunawili district, b. 151",0.68,"molasses, sweet, cocoa",3.25,3,"B,S,C"
4,Nanea,U.S.A.,2013.0,U.S.A.,Criollo Blend,0.72,"sandy, spicy, earthy",3.50,0,None
...,...,...,...,...,...,...,...,...,...,...
2652,Bahen & Co.,Australia,2012.0,Madagascar,Sambirano,0.80,"unrefined, flat, grassy",3.00,2,"B,S"
2653,Mast Brothers,U.S.A.,2012.0,Blend,Madagascar,0.75,"gritty, overly tart, sour",2.50,2,"B,S"
2654,Mast Brothers,U.S.A.,2012.0,Venezuela,Chuao,0.75,"gritty, sour, sweet",2.75,2,"B,S"
2655,Bahen & Co.,Australia,2012.0,Brazil,Bahia,0.70,"chalky, intense, chemical",2.50,2,"B,S"
2656,NaN,NaN,NaN,NaN,NaN,0.72,NaN,NaN,0,NaN

In [64]:
# Flin 45
# This is looking into the Peru info as it also has a wide variety of stats
Peru= choc_bar_ratings_df[choc_bar_ratings_df['Company Location'] == 'Peru']

In [65]:
Peru

,Company (Manufacturer),Company Location,Review Date,Country of Bean Origin,Specific Bean Origin or Bar Name,Cocoa Percent,Most Memorable Characteristics,Rating,Num_of_Ingredients,Specific Ingredients
134,Pascha,Peru,2013.0,Peru,Peru,0.70,"gritty, sweet, off",2.50,4,"B,S,C,V"
135,Pascha,Peru,2013.0,Peru,Peru,0.70,"gritty, earthy, melon",2.75,4,"B,S,C,V"
144,Amazona,Peru,2013.0,Peru,"LamasdelChanka, San Martin, Oro Verde coop",0.70,"oily, vanilla, melon, cocoa",3.25,3,"B,S,C"
145,Amazona,Peru,2013.0,Peru,"Bellavista Gran Pajeten, San Martin",0.70,"oily, vegetal, nutty, cocoa",3.50,3,"B,S,C"
480,Bakau,Peru,2015.0,Peru,"Bambamarca, 2015",0.72,"molasses, caramel, pungent",2.75,3,"B,S,C"
481,Bakau,Peru,2015.0,Peru,"Huallabamba, 2015",0.72,"black pepper, cardamom",3.50,3,"B,S,C"
965,Marana,Peru,2016.0,Peru,Cusco,0.72,"smokey, dirty, sour",2.75,3,"B,S,C"
966,Shattell,Peru,2016.0,Peru,Tingo Maria,0.70,"earthy, roasty, vegetal",3.25,3,"B,S,C"
1242,Nina,Peru,2018.0,Peru,Chazuta,0.80,"pungent, grape, sour",3.00,3,"B,S,C"
1313,Tribar,Peru,2018.0,Peru,Ucayali,0.67,"powdery, complex, rubber",3.00,3,"B,S,C"
1322,Tribar,Peru,2018.0,Peru,"Piura, Gran Chilique",0.80,"sweet, pungent grape, acidic",3.50,3,"B,S,C"
1752,Marana,Peru,2021.0,Peru,"San Martin, Allima coop",0.71,"smoked nuts, tang",3.25,3,"B,S,C"
1753,Marana,Peru,2021.0,Peru,"Piura, Norandino coop, cacao blanco",0.68,"mild orange, herbaceous",3.50,3,"B,S,C"
1754,Cacaosuyo,Peru,2021.0,Peru,Chuncho-Cuzco,0.68,"herbal, cocoa tea",3.50,2,"B,S"
1755,Cacaosuyo,Peru,2021.0,Peru,Piura Select,0.80,chocolate and grapes,4.00,2,"B,S"
1758,Cacaosuyo,Peru,2021.0,Peru,"Lakuna, Amazonas, silvestre",0.71,"complex, floral, spicy, fruit",3.50,2,"B,S"
1759,Cacaosuyo,Peru,2021.0,Peru,Cuzco,0.70,"smooth, slow, mild grape",3.50,2,"B,S"
2228,Machu Picchu Trading Co.,Peru,2010.0,Peru,Peru,0.70,"extremely sweet, vanilla",2.25,0,None
2377,La Oroquidea,Peru,2011.0,Peru,Peruvian Amazon,0.70,"peanut butter, burnt rubber",2.50,0,None
2378,Machu Picchu Trading Co.,Peru,2011.0,Peru,Peru,0.70,"vanilla, strong chemical",1.50,0,None
2416,Shattell,Peru,2011.0,Peru,Porcelana,0.70,"strong spice, perfume, roasty",3.50,3,"B,S,C"
2507,Orquidea,Peru,2012.0,Peru,Peru,0.71,"dry, banana, molasses",3.00,4,"B,S,C,L"
2508,Orquidea,Peru,2012.0,Peru,Peru,0.72,"sandy, molasses, brownie",3.00,4,"B,S,C,L"

In [66]:
# The Peruvian specifics are here below
Peru.groupby('Num_of_Ingredients')['Cocoa Percent'].unique()

Num_of_Ingredients
0                                 [0.7]
2                [0.68, 0.8, 0.71, 0.7]
3    [0.7, 0.72, 0.8, 0.67, 0.71, 0.68]
4                     [0.7, 0.71, 0.72]
Name: Cocoa Percent, dtype: object

In [67]:
# from Flin 45 
# what this is doing is looking into a specific country for examples
#  what this is doing is looking into Venezuela info as it contains a much  larger variety of stats
Venezuela = choc_bar_ratings_df[choc_bar_ratings_df['Company Location'] == 'Venezuela']

In [68]:
Venezuela

,Company (Manufacturer),Company Location,Review Date,Country of Bean Origin,Specific Bean Origin or Bar Name,Cocoa Percent,Most Memorable Characteristics,Rating,Num_of_Ingredients,Specific Ingredients
374,Franceschi,Venezuela,2014.0,Venezuela,"Choroni, batch 210414",0.70,"intense, tobacco, nuts",3.50,3,"B,S,C"
375,Franceschi,Venezuela,2014.0,Venezuela,"Ocumare, batch 210414",0.60,"caramel, dairy",3.75,3,"B,S,C"
408,Cacao de Origen,Venezuela,2014.0,Venezuela,"Agua Fria; Sucre region, H. La Trinidad",0.75,"intense, earthy, fuel",2.50,2,"B,S"
409,Cacao de Origen,Venezuela,2014.0,Venezuela,"Macuare; Miranda; Chloe formula, H. La Trinidad",0.70,"nutty, intense, leathery",3.25,2,"B,S"
410,Cacao de Origen,Venezuela,2014.0,Venezuela,"Chuao, Aragua region, H. La Trinidad",0.70,"bright fruit, strawberry",3.50,2,"B,S"
414,Cacao de Origen,Venezuela,2014.0,Venezuela,"Chuao, Aragua region, H. La Trinidad",0.70,"fruity, nutty, brownie",3.75,2,"B,S"
730,El Rey,Venezuela,2015.0,Venezuela,San Joaquin,0.72,"spicy, caramel, vanilla",3.75,5,"B,S,C,V,L"
736,Cacao de Origen,Venezuela,2015.0,Venezuela,Hacienda la Trinidad,0.70,"intense, black licorice, nutty",3.25,2,"B,S"
755,Cacao de Origen,Venezuela,2015.0,Venezuela,Chuao,0.66,"assertive, fruity, acidic",3.50,2,"B,S"
760,Cacao de Origen,Venezuela,2015.0,Venezuela,Rio Caribe,0.72,"spicy, nutty, ends sour",3.25,2,"B,S"
870,Suruca Chocolate,Venezuela,2016.0,Venezuela,Venezuela,0.70,"sticy, nutty, roasty, off notes",2.75,3,"B,S,C"
871,Suruca Chocolate,Venezuela,2016.0,Venezuela,Venezuela,0.72,"sticky, sweet, nutty, roasty",3.00,3,"B,S,C"
1136,Franceschi,Venezuela,2018.0,Venezuela,Rio Caribe,0.70,"large grits, sweet",2.50,4,"B,S,C,L"
1149,El Rey,Venezuela,2008.0,Venezuela,"Carenero Superior, Apamate",0.65,"sandy, banana, sour",2.50,5,"B,S,C,V,L"
1150,El Rey,Venezuela,2008.0,Venezuela,"Carenero Superior, Bucare",0.61,"gritty, sweet, banana, smoke",2.50,5,"B,S,C,V,L"
1151,El Rey,Venezuela,2008.0,Venezuela,"Carenero Superior, Mijao",0.65,"muted, cherry, banana",3.00,5,"B,S,C,V,L"
1176,Bitacora,Venezuela,2018.0,Venezuela,Aragua,0.75,"smooth texture, earthy, nutty",3.50,4,"B,S,C,L"
1182,Bitacora,Venezuela,2018.0,Venezuela,Merida,0.70,"gritty, spicy, earthy",3.00,4,"B,S,C,L"
1183,Bitacora,Venezuela,2018.0,Venezuela,Carabobo,0.67,"fatty, bland, nutty",3.00,4,"B,S,C,L"
1195,Franceschi,Venezuela,2018.0,Venezuela,"Sur del Lago, Zulia",0.72,large grits,3.00,3,"B,S,C"
1196,Franceschi,Venezuela,2018.0,Venezuela,"Carenero, Miranda",0.70,"dried fruit, large grits",3.25,3,"B,S,C"
1216,Franceschi,Venezuela,2018.0,Venezuela,"Cuyagua, batch 4, lot DC2.3",0.70,nutty,3.50,2,"B,S"
1220,Franceschi,Venezuela,2018.0,Venezuela,"Chuao, batch 4, Lot DH17",0.70,"sl. dry, gritty, fruity, nuts",3.00,2,"B,S"
1341,Cacao de Origen,Venezuela,2018.0,Venezuela,Carupano Pintao,0.65,"sandy, chalky, earthy",2.75,2,"B,S"
1386,Cacao de Origen,Venezuela,2019.0,Venezuela,"Barlovento, Familia Rojas",0.90,"high astringent, sandy, grass",2.50,2,"B,S"
1387,Cacao de Origen,Venezuela,2019.0,Venezuela,Canoabo,0.72,"raspberry, dirty, sour",3.00,2,"B,S"
2038,El Rey,Venezuela,2006.0,Venezuela,"Carenero Superior, Gran Saman",0.70,"gritty, chalky, earthy, sour",2.75,5,"B,S,C,V,L"
2140,El Rey,Venezuela,2009.0,Venezuela,"Rio Caribe, Cariaco",0.70,"very sweet, marshmallow",2.75,5,"B,S,C,V,L"
2141,El Rey,Venezuela,2009.0,Venezuela,"Rio Caribe, Macuro",0.70,"sandy,bold,cherry,peanut butter",3.00,5,"B,S,C,V,L"
2564,Franceschi,Venezuela,2012.0,Venezuela,Canoabo,0.68,"nutty, dried fruit",3.75,3,"B,S,C"
2568,Franceschi,Venezuela,2012.0,Venezuela,Sur del Lago,0.74,"grits, hazelnut, rum",3.50,3,"B,S,C"

In [69]:
# flin 45 
# what this is doing is going into some more details and specifics on the Venezuela data
Venezuela.groupby('Num_of_Ingredients')['Cocoa Percent'].unique()

Num_of_Ingredients
2    [0.75, 0.7, 0.66, 0.72, 0.65, 0.9]
3          [0.7, 0.6, 0.72, 0.68, 0.74]
4                     [0.7, 0.75, 0.67]
5               [0.72, 0.65, 0.61, 0.7]
Name: Cocoa Percent, dtype: object

In [70]:
# again assessing the shape of the data frame
choc_bar_ratings_df.shape

(2657, 10)

5.  This is Exporting all the above Data

In [71]:

# exporting the cleaned flavors of cacao data but it needs to be in the "prepared data"
choc_bar_ratings_df.to_csv(r'C:\Users\rdpor\anaconda3\Scripts\CAREER FOUNDRY ACHIEVMENT 6\Prepared Data\choc_bar_ratings_df_clean.csv', index=False)